name: Docs www pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - packages/www/**
jobs:
  www-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    name: WWW workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.9.2'
      - name: Install dependencies
        run: pnpm install
      - name: Build lib
        run: pnpm lib:build
      - name: Build www
        run: pnpm www:build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
