name: Docs www pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - packages/www/**
jobs:
  www-workflow:
    runs-on: ubuntu-latest
    name: WWW workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.9.2'
      - name: Install dependencies
        run: pnpm install
      - name: Build lib
        run: pnpm lib:build
      - name: Build www
        run: pnpm www:build
      - name: Set up Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Authenticate GitHub Pages
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Deploy www
        run: pnpm www:deploy-docs
